### PR TITLE
Data driven achievements and loading code changes

### PR DESCRIPTION
**Pull request by Craiel**
Hello,

saw your post on reddit and wanted to tinker a bit with the code.
I made a couple of changes to the achievements to make them easier and shorter to create.
You are doing a lot of repetition in code and html that is not really required, take a look at my changes if you want them or just take some inspiration from it :).

Let me know what you think, if you want i can continue to work on some more things.
Craiel

### CODE REVIEW

**Comment by sparticle999** [comment]
Thanks for this, I will take a look and let you know what I think!

**Comment by sparticle999** [comment]
hey, I've seen what you've done and so far I like it. I tried to test it on https://craiel.github.io/SpaceCompany/, but there was a bug: 
image

**Comment by Craiel** [comment]
huh odd, does not happen in my chrome, i suspect it's an order problem, try moving variable.js before game.js in index.html

**Comment by sparticle999** [comment]
why don't the icons work for the achievements?
image

**Comment by sparticle999** [comment]
and also, with the icons, there aren't any tooltips?

**Comment by Craiel** [comment]
I ran it locally for testing thats why i didn't have the issue, looks like github is case sensitive.
I pushed a fix into the repo that should have the icons show up again.

scrn

**Comment by Craiel** [comment]
Tested in firefox as well, shows up properly in GitHub now:

scrn

**Comment by sparticle999** [comment]
no tooltips? how would I know which achivement does what?

**Comment by Craiel** [comment]
There are tooltips, you dont have them? Check both the screenshots you can see its there

**Comment by sparticle999** [comment]
my mistake, they are there

**Comment by sparticle999** [comment]
However, I'm not really a fan of horizontal scrolling. Do you think you could make the maximum 8 icons per row? I don't mind fewer

**Comment by sparticle999** [comment]
also, do you know a way to make there only show one achievemnt in a set? e.g. the achievement says get 1 miner, and after doing that, it changes to get 10 miners, but it could change colour, or get a star underneath it or something? That would be great, although I'm not really sure how to do it.

**Comment by Craiel** [comment]
Yeah set is easy enough, i took the html from the way it was so didnt modify anything there but i can take a stab at changing the layout. Would you still want the categories if you have the set?

**Comment by sparticle999** [comment]
I think have categories for resources and then producers. Not much need to subdivide more than that

**Comment by Craiel** [comment]
Submitted the change, it's now tiered, the border color might be too much maybe, take a look

**Comment by Craiel** [comment]
scrn

**Comment by sparticle999** [comment]
That looks really good! I'll test it out when I get home, but it looks promising. Thanks so much! I'll put your name in the credits page when I merge your fork.

**Comment by sparticle999** [comment]
Ok, tests well too. No visible bugs, apart from the fact that on loading the page, you get the achievements incrementing to the current value every second. Try refreshing and then jumping to the achievements tab and you will see it changing.

**Comment by sparticle999** [comment]
Also, I've never used grunt before and although your code works fine, I am a novice programmer and don't completely understand some of how it works. Are you on the space company discord?

**Comment by Craiel** [comment]
Yeah the increment after refresh was cause the save / load was not working properly, just fixed it.

I'll see if i can come on discord, im at work so it's not so easy. Grunt is pretty straight forward, i made it so it's optional right now. All you need is to install nodejs: https://nodejs.org/en/

Then it's a one-time setup in the project with a command prompt:
npm install -g grunt-cli
npm install

afterwards you can "build" the project by just running "grunt" in command line.
What it will do is join all the .js files together and minify them into a "SpaceCompany.min.js"
There is some decent documentation here: https://gruntjs.com/getting-started

**Comment by sparticle999** [comment]
Thanks for this.

**Comment by sparticle999** [comment]
I will merge it, but could you fix this? On loading the page, you get the achievements incrementing to the current value every second. Try refreshing and then jumping to the achievements tab and you will see it changing.

**Comment by sparticle999** [comment]
image
image
I merged it, but this error came up on my site afterwards

**Comment by sparticle999** [comment]
The top is mine, the bottom is yours. At the time, they had the same code as I had just merged it

**Comment by Craiel** [comment]
Not sure why that would be if the code is the same, since it runs fine in my github.
I'm not sure how to fix this since i can't test on your branch since you reverted it.

and i already did fix the achievement incrementing on load as i mentioned:

"the increment after refresh was cause the save / load was not working properly, just fixed it."

**Comment by Craiel** [comment]
I can open a new pull request if you want to try again?

actually that won't work now, you'd have to undo your revert

**Pull request merged**
