### PR TITLE
Re-worked energy-mass conversion UI

### PR DESCRIPTION
**Pull request by AndreasDybdahl**
Had to put display: none on old table or game breaks.

### CODE REVIEW

**Comment by mendel3** [comment]
Can I see a picture of it?

**Comment by sparticle999** [comment]
does this work, or is it just the design?

**Comment by AndreasDybdahl** [comment]
It works

**Comment by mendel3** [comment]
I found a bug, 
screen shot 2017-05-30 at 2 53 11 pm
It says Energy, instead of plasma. The coding is correct and it takes plasma and makes meteorites, 
it just a visual error

**Comment by AndreasDybdahl** [comment]
Dammit :P

**Pull request merged**
